# -*- coding: utf-8 -*-
"""Diabetes_Progression_Statistical_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iw-YESNZC0V-iW30rRSqDPdoK_hE5Z8d
"""

!pip install statsmodels -q

import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import statsmodels.api as sm
from scipy import stats
import json

# 1. Load data
data = load_diabetes(as_frame=True)
df = data.frame.copy()
df.rename(columns={"target": "disease_progression"}, inplace=True)

results = {}
results["n_samples"] = int(df.shape[0])
results["n_features"] = int(df.shape[1] - 1)
results["features"] = list(data.feature_names)

# 2. Correlation with target
corrs = df.corr()["disease_progression"].drop("disease_progression").sort_values(ascending=False)
results["correlation_with_target"] = {k: round(float(v), 4) for k, v in corrs.items()}

# 3. OLS regression with statistical inference
X = df[data.feature_names]
y = df["disease_progression"]
X_sm = sm.add_constant(X)
ols_model = sm.OLS(y, X_sm).fit()

results["ols_r_squared"] = round(float(ols_model.rsquared), 4)
results["ols_adj_r_squared"] = round(float(ols_model.rsquared_adj), 4)
results["ols_f_statistic"] = round(float(ols_model.fvalue), 4)
results["ols_f_pvalue"] = float(ols_model.f_pvalue)

coef_table = pd.DataFrame({
    "coefficient": ols_model.params,
    "std_err": ols_model.bse,
    "t_value": ols_model.tvalues,
    "p_value": ols_model.pvalues,
})
coef_table = coef_table.round(4)
results["coefficient_table"] = coef_table.to_dict(orient="index")

sig_predictors = coef_table[(coef_table["p_value"] < 0.05) & (coef_table.index != "const")]
results["significant_predictors_p<0.05"] = list(sig_predictors.index)

# 4. Hypothesis test: does sex have a significant effect?
sex_pvalue = float(coef_table.loc["sex", "p_value"])
results["hypothesis_test_sex_effect"] = {
    "null_hypothesis": "Sex has no effect on disease progression, controlling for other variables",
    "p_value": round(sex_pvalue, 4),
    "conclusion": "Reject H0 (significant effect)" if sex_pvalue < 0.05 else "Fail to reject H0 (no significant effect)",
}

# 5. Predictive model: train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
mae = float(mean_absolute_error(y_test, y_pred))
test_r2 = float(r2_score(y_test, y_pred))

results["test_set_metrics"] = {
    "rmse": round(rmse, 2),
    "mae": round(mae, 2),
    "r_squared": round(test_r2, 4),
    "n_test_samples": int(len(y_test)),
}

baseline_pred = np.full_like(y_test, y_train.mean(), dtype=float)
baseline_rmse = float(np.sqrt(mean_squared_error(y_test, baseline_pred)))
results["baseline_mean_rmse"] = round(baseline_rmse, 2)
results["rmse_improvement_over_baseline_pct"] = round((1 - rmse / baseline_rmse) * 100, 1)

# 6. Residual diagnostics
residuals = y_test - y_pred
shapiro_stat, shapiro_p = stats.shapiro(residuals)
results["residual_normality_test"] = {
    "test": "Shapiro-Wilk",
    "statistic": round(float(shapiro_stat), 4),
    "p_value": round(float(shapiro_p), 4),
    "residuals_approx_normal": bool(shapiro_p > 0.05),
}

with open("results.json", "w") as f:
    json.dump(results, f, indent=2)

print(json.dumps(results, indent=2))

from google.colab import files
files.download('results.json')

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))

# Left chart: Predicted vs Actual
axes[0].scatter(y_test, y_pred, alpha=0.6, color="#2563eb", edgecolor="white", s=40)
lims = [min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())]
axes[0].plot(lims, lims, "--", color="#9ca3af", linewidth=1.5)
axes[0].set_xlabel("Actual disease progression")
axes[0].set_ylabel("Predicted disease progression")
axes[0].set_title("Predicted vs. Actual (Test Set)")

# Right chart: Feature correlation with target
corrs_sorted = df.corr()["disease_progression"].drop("disease_progression").sort_values()
colors = ["#ef4444" if v < 0 else "#2563eb" for v in corrs_sorted.values]
axes[1].barh(corrs_sorted.index, corrs_sorted.values, color=colors)
axes[1].set_title("Feature Correlation with Target")
axes[1].set_xlabel("Pearson correlation")

plt.tight_layout()
plt.savefig("regression_charts.png", dpi=150)
plt.show()